/// <reference types="node" />

// Every committed document cites the code by `path:line`, and every one of those
// anchors goes stale the moment a line is inserted above it. A pre-merge review of
// this repository found eleven stale anchors in README.md alone, and the pass that
// fixed them introduced thirty more, because the code moved underneath the edit.
//
// So the anchors are checked rather than trusted: the file must exist, the line must
// be inside it, and the line must not be blank — a citation landing on whitespace is
// the signature of a block that shifted. What this cannot check is a citation that
// drifted onto some *other* real line; for that, quote the symbol in the prose and a
// reader can see the mismatch. That blind spot is not theoretical: pinning the CI
// runner moved every job in `ci.yml` down nine lines, and thirteen anchors across four
// documents went on resolving to a real line inside the wrong job. So run this after
// any commit that shifts lines in a cited file, not only when editing a document, and
// reread what the prose claims the line says.
//
// It also refuses the two things that must never reach a committed file: an absolute
// filesystem path, and a reference to the gitignored `.local/` scratch directory.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

const rootDir = path.resolve(import.meta.dirname, "..");

/** `src/spatial/spatial.ts:188` or `docs/adr/0009-hidden-candidates.md:80-97`. */
const CITATION =
  /`([A-Za-z0-9_@./-]+\.(?:ts|tsx|js|jsx|json|ya?ml|md|css|scss|html)):(\d+)(?:-(\d+))?`/g;
// The licence record cites the predecessor implementation by design: establishing the MIT
// origin and the copyright holder is what that document is for, and the paths it cites are
// the evidence. It is the only document in this tree allowed to cite a path that resolves
// nowhere here; everywhere else, such a path is the house-rule break reported below.
const PROVENANCE_RECORD = "docs/adr/0002-license-and-copyright.md";
/** This repository's own top-level directories — what makes a path unambiguously ours. */
const OWN_ROOTS = ["src/", "scripts/", "playground/", ".github/", "docs/adr/"];
// A drive letter, but not the tail of a URL scheme: the `s` of `https://` is a
// letter followed by `:/` too, so the lookbehind for a word character is what tells
// `D:/DevSoftware` from `https://bun.sh`.
const ABSOLUTE = /(?<!\w)[A-Za-z]:[\\/]|\/Users\/|\/home\//;
const SCRATCH = /(?:^|[\s(`"'])\.local\//;
/** `[ADR-0003](0003-extraction-scope.md)` — the target, fragment and all. */
const LINK = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
/** Nothing on the filesystem to resolve: another host, a mail client, a heading here. */
const EXTERNAL = /^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i;

interface Problem {
  readonly file: string;
  readonly line: number;
  readonly what: string;
}

// `CHANGELOG.md` is generated by release-please from commit subjects, and it is the one
// document whose anchors are *supposed* to go stale: an entry describes the code as it was
// at that version, and a later release cannot rewrite it. Gating it would either fail the
// release that produced it or force a rule that a commit subject may carry no `path:line`,
// which is a worse trade — the subject is the release note.
const GENERATED = new Set(["CHANGELOG.md"]);

// These two belong with the patterns at the top of this file and cannot go there:
// ADR-0012 cites the block above by line, and the citation gate is the last file in
// the tree that may quietly move a line someone else points at.
/** Any backticked path, quoted or not, with or without the `:line` tail `CITATION` requires. */
const PATH_REFERENCE =
  /`["']?((?:\.{1,2}\/)?[A-Za-z0-9_@.][A-Za-z0-9_@./-]*\.(?:ts|tsx|js|jsx|json|ya?ml|md|css|scss|html))["']?(?::\d+(?:-\d+)?)?`/g;
/** `` `:49` `` — a line in whichever file the prose named last. */
const BARE_ANCHOR = /`:(\d+)(?:-(\d+))?`/g;

/** One of the two, found at `at` so a line can be read left to right rather than twice. */
interface Written {
  readonly at: number;
  readonly reference?: string;
  readonly start?: number;
  readonly end?: number;
}

function tracked(): string[] {
  const result = spawnSync("git", ["ls-files", "*.md"], { cwd: rootDir, encoding: "utf8" });
  if (result.status !== 0) throw new Error("git ls-files failed");
  return result.stdout
    .split("\n")
    .filter((entry) => entry.trim() !== "")
    .filter((entry) => !GENERATED.has(entry));
}

const lineCache = new Map<string, string[] | null>();

function linesOf(relative: string): string[] | null {
  const cached = lineCache.get(relative);
  if (cached !== undefined) return cached;
  let lines: string[] | null;
  try {
    lines = readFileSync(path.join(rootDir, relative), "utf8").split("\n");
  } catch {
    lines = null;
  }
  lineCache.set(relative, lines);
  return lines;
}

/** Every tracked file, indexed by basename, so `focus-ring.ts` in prose finds its one path. */
function byBasename(): Map<string, string[]> {
  const result = spawnSync("git", ["ls-files"], { cwd: rootDir, encoding: "utf8" });
  if (result.status !== 0) throw new Error("git ls-files failed");
  const index = new Map<string, string[]>();
  for (const entry of result.stdout.split("\n")) {
    const file = entry.trim();
    if (file === "") continue;
    const base = file.slice(file.lastIndexOf("/") + 1);
    const known = index.get(base);
    if (known === undefined) index.set(base, [file]);
    else known.push(file);
  }
  return index;
}

const basenames = byBasename();

// What a reader does with a name in backticks: take it as written if it is a path from
// the root, and otherwise as a basename, which is unambiguous only while one file in the
// tree carries it. A name that resolves to neither resolves to nothing — and a name that
// resolves to nothing is not a file the prose named, which is the rule that matters at
// the call site below.
function named(reference: string): string | null {
  const written = reference.replace(/^\.\//, "");
  if (existsSync(path.join(rootDir, written))) return written;
  const candidates = basenames.get(written.slice(written.lastIndexOf("/") + 1)) ?? [];
  return candidates.length === 1 ? (candidates[0] ?? null) : null;
}

const problems: Problem[] = [];
const unprefixed: Problem[] = [];
let checked = 0;
let provenance = 0;
let shorthand = 0;
let links = 0;
let anchors = 0;
let inherited = 0;

for (const document of tracked()) {
  const text = readFileSync(path.join(rootDir, document), "utf8");
  const documentLines = text.split("\n");
  /** The file the prose named last, which is what a bare `:NNN` below resolves against. */
  let subject: string | null = null;

  for (const [index, line] of documentLines.entries()) {
    const at = index + 1;

    if (ABSOLUTE.test(line)) {
      problems.push({ file: document, line: at, what: `absolute filesystem path: ${line.trim()}` });
    }
    if (SCRATCH.test(line)) {
      problems.push({ file: document, line: at, what: `reference to the gitignored .local/` });
    }

    // A `path:line` citation is checked above, but `[ADR-0003](0003-extraction-scope.md)`
    // was not checked by anything — and those links are the dense part of this tree:
    // one document is the target of twenty-four of them. Deleting or renaming a file
    // therefore used to leave dead links that every gate reported as green.
    for (const match of line.matchAll(LINK)) {
      const target = match[1];
      if (target === undefined || EXTERNAL.test(target)) continue;

      // The fragment is the reader's business, not the filesystem's; an empty path
      // before it means the link points inside the document it is written in.
      const file = target.split("#")[0] ?? "";
      if (file === "") continue;

      const resolved = file.startsWith("/")
        ? path.join(rootDir, file.slice(1))
        : path.resolve(rootDir, path.dirname(document), decodeURIComponent(file));

      links += 1;
      if (!existsSync(resolved)) {
        problems.push({ file: document, line: at, what: `links to ${file}, which does not exist` });
      }
    }

    for (const match of line.matchAll(CITATION)) {
      const [, cited, startText, endText] = match;
      if (cited === undefined || startText === undefined) continue;

      // `spatial.ts:198` and `.../spatial.ts:60` — a citation carrying no directory, or
      // the `.../` elision. There is nothing to resolve them against, so they are counted
      // and left alone. That is a blind spot and it cost something: a root-level file has
      // no `/` either, so `README.md:53-62` in ADR-0006 was classified here and went on
      // pointing at a blank line that the rule below would have caught at once.
      // The documents no longer write anchors this way. The licence record is the last
      // one left, and its paths are a frozen external commit that cannot drift with ours.
      if (!cited.includes("/") || cited.startsWith("...")) {
        shorthand += 1;
        continue;
      }

      // Only a path rooted in one of this repository's own top-level directories is
      // unambiguously about this repository. Anything else that resolves to no file —
      // `focus/tabbable.ts`, `../../README.md` — is a path the reader cannot follow:
      // reported, not fatal, because the fix is prose and nobody is being sent
      // anywhere wrong. The licence record is the one document exempt from this.
      if (!OWN_ROOTS.some((root) => cited.startsWith(root))) {
        const lines = linesOf(cited);
        if (lines === null) {
          if (document === PROVENANCE_RECORD) {
            provenance += 1;
            continue;
          }
          unprefixed.push({ file: document, line: at, what: cited });
          continue;
        }
      }

      checked += 1;
      const lines = linesOf(cited);
      if (lines === null) {
        problems.push({ file: document, line: at, what: `cites ${cited}, which does not exist` });
        continue;
      }

      const start = Number(startText);
      const end = endText === undefined ? start : Number(endText);
      if (end < start) {
        problems.push({
          file: document,
          line: at,
          what: `${cited}:${start}-${end} runs backwards`,
        });
        continue;
      }
      if (end > lines.length) {
        problems.push({
          file: document,
          line: at,
          what: `${cited}:${startText}${endText === undefined ? "" : `-${endText}`} is past the end of the file (${lines.length} lines)`,
        });
        continue;
      }
      // A range is allowed to contain blank lines; its first and last must not be,
      // because that is what a block boundary looks like when it has moved.
      for (const edge of end === start ? [start] : [start, end]) {
        if ((lines[edge - 1] ?? "").trim() === "") {
          problems.push({
            file: document,
            line: at,
            what: `${cited}:${edge} is a blank line — the anchor has drifted`,
          });
        }
      }
    }

    // A path is written in full once and the lines around it are then cited as `:NNN`.
    // Two hundred and twenty-three of those anchors are in this tree and nothing checked
    // a single one: the pattern above needs a path, and a bare anchor has none. They are
    // checked here against the file the prose named last, which is what a reader resolves
    // them against too — so the two must be read in the order they appear on the line, not
    // one pattern after the other, or `a.ts:1 … :2 … b.ts:3 … :4` sends `:2` to the wrong
    // file. A name that resolves to nothing leaves the subject alone rather than taking
    // it: in ADR-0010 the entry `debug.js` sits in a sentence about `scripts/size-budget.ts`,
    // and letting that name win would have pointed the next anchor at a build artefact.
    const written: Written[] = [];
    for (const match of line.matchAll(PATH_REFERENCE)) {
      if (match[1] !== undefined) written.push({ at: match.index ?? 0, reference: match[1] });
    }
    for (const match of line.matchAll(BARE_ANCHOR)) {
      if (match[1] === undefined) continue;
      const start = Number(match[1]);
      written.push({
        at: match.index ?? 0,
        start,
        end: match[2] === undefined ? start : Number(match[2]),
      });
    }
    written.sort((one, other) => one.at - other.at);

    for (const entry of written) {
      if (entry.reference !== undefined) {
        subject = named(entry.reference) ?? subject;
        continue;
      }
      const start = entry.start;
      const end = entry.end;
      if (start === undefined || end === undefined) continue;

      // The licence record's anchors belong to the predecessor repository, and this one
      // has a `geometry.ts` of its own: resolving them here does not fail, it succeeds
      // against the wrong file and reports a line that has nothing to do with the prose.
      // That is worse than not checking them, so they are counted and left alone — the
      // same exemption the full citations above already carry.
      if (document === PROVENANCE_RECORD) {
        inherited += 1;
        continue;
      }
      if (subject === null) {
        problems.push({
          file: document,
          line: at,
          what: `\`:${start}\` before any file is named — nothing to resolve it against`,
        });
        continue;
      }

      const lines = linesOf(subject);
      if (lines === null) continue;

      anchors += 1;
      if (end < start) {
        problems.push({
          file: document,
          line: at,
          what: `${subject}:${start}-${end} runs backwards`,
        });
        continue;
      }
      if (end > lines.length) {
        problems.push({
          file: document,
          line: at,
          what: `\`:${start}${entry.end === start ? "" : `-${end}`}\` is ${subject}:${end}, past the end of the file (${lines.length} lines)`,
        });
        continue;
      }
      for (const edge of end === start ? [start] : [start, end]) {
        if ((lines[edge - 1] ?? "").trim() === "") {
          problems.push({
            file: document,
            line: at,
            what: `\`:${edge}\` is ${subject}:${edge}, a blank line — the anchor has drifted`,
          });
        }
      }
    }
  }
}

if (unprefixed.length > 0) {
  console.log("");
  console.log(
    `${unprefixed.length} cited path${unprefixed.length === 1 ? " resolves" : "s resolve"} nowhere in this repository.` +
      ` Every cited path is a path in this repository, written from the repository root, at a real` +
      ` line you have opened; a claim with no such line carries the inherited marker and no path at all:`,
  );
  for (const one of unprefixed) console.log(`  ${one.file}:${one.line} — ${one.what}`);
}

console.log("");
console.log(
  `checked ${checked} citation${checked === 1 ? "" : "s"}, ${anchors} bare anchor${anchors === 1 ? "" : "s"} and ${links} link${links === 1 ? "" : "s"} into this repository across ${tracked().length} documents` +
    ` (${provenance + inherited} in the licence record and ${shorthand} written in shorthand, neither resolvable here)`,
);

if (problems.length > 0) {
  console.error("");
  for (const problem of problems) {
    console.error(`${problem.file}:${problem.line} — ${problem.what}`);
  }
  console.error(`\n${problems.length} citation problem${problems.length === 1 ? "" : "s"}`);
  process.exit(1);
}

console.log("every citation resolves");
